#!/bin/bash -eu

python michizure.py > work/michizure.json

.venv/bin/aws cloudformation validate-template --template-body "$(cat work/michizure.json)"

echo ''
echo "$(tput setaf 2)Template is valid.$(tput sgr0)"
echo ''
